title: LYSZT -Portfólios e Projetos Relevantes
description: Welcome to the portfolio of João Luís Almeida Santos (Lyszt Kaldwin), a skilled Developer & Designer. Explore UI/UX design, web & software solutions, and video production services tailored to elevate your business. Discover recent projects and learn about João's experience in the tech industry. Powered by Lygon Xin.
google_analytics: G-QGFB5G2G4P
avatar: https://avatars.githubusercontent.com/u/116316121?v=4

# Flags below are optional

# Includes an icon in the footer for each username you enter
footer-links:
  email: jluis.kaldwin@gmail.com
  github: barryclark/jekyll-now
  instagram: lyszt_kaldwin
  linkedin: lyszt
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: user/mementoskai

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://lyszt.github.io

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
